services:
  - type: web
    name: n8n-service
    env: docker
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.cyiwsondajjgnnuvskcy.supabase.co
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: SKOHge8y_#2025!
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: CHANGE_THIS_TO_A_SECURE_RANDOM_STRING
      - key: GENERIC_TIMEZONE
        value: America/Lima
      - key: TZ
        value: America/Lima
      - key: N8N_LOG_LEVEL
        value: info
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "168"
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none
      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
        value: false
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: false
    disk:
      name: n8n-disk
      mountPath: /home/node/.n8n
      sizeGB: 5
